---
title: "Raport"
author: "Maria Kałuska, Marcelina Kurek"
date: "14 05 2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(readr)
library(ggplot2)
```
```{r, include=FALSE}
busyStations <- data.table(read_csv("busy_stations.csv"))
endStations <- data.table(read_csv("end_stations.csv"))
Routes <- data.table(read_csv("routes_to_plot.csv"))
```
Najbardziej oblegane stacje w Nowym Yorku
```{r, include=TRUE, cache=TRUE}
ggplot(busyStations, aes(x=longitude, y=latitude, color=N)) + 
  geom_point(alpha=0.2) +
  scale_size(range=c(.1, 10)) +
  scale_color_gradient(low="blue", high="red")
```
Najczęstsze stacje docelowe
```{r, include=TRUE, cache=TRUE}
ggplot(endStations, aes(x=longitude, y=latitude, color=N)) + 
  geom_point(alpha=0.4) +
  scale_size(range=c(.1, 10)) +
  scale_color_gradient(low="blue", high="red")
```
100 najbardziej uczęszczanych tras
```{r, include=TRUE}
ggplot(Routes, aes(x=`start longitude`, y=`start latitude`, group=id)) +
  geom_point(size=2, color="blue") +
  geom_line(color="red")
```

```{r, include=TRUE}
ggplot(data=dane_do_wykresu, aes(x=`rok urodzenia`, y=`liczba osób`, fill = as.factor(gender))) +
  geom_bar(stat="identity")+
  geom_text(aes(y=0, label=10), vjust=1.6, 
            color="white", size=3.5)+
  scale_fill_brewer(palette = "Dark2", name = "Płeć", labels = c("Brak danych", "Mężczyzna", "Kobieta") )+
  ggtitle("Użytkownicy rowerów miejskich, którzy wypożyczają rowery na najdłuższy okres czasu")
```
```{r, include=TRUE}
#wykres
ggplot(Weekend_vs_zwykly, aes(x=tydzien ,y=srednia, group=weekend, colour=weekend)) +
  geom_point()+
  geom_line(size = 1)+
  ggtitle("Średnia ilość wypożyczeń w ciągu dnia w kolejnych tygodniach")+
  scale_colour_brewer(palette = "Set1", name = "", labels = c("Dni powszednie", "Weekendy") )+
  ylab("Ilość wypożyczeń [szt]")+
  xlab("")
```

```{r, include=TRUE}
paleta <- palette(brewer.pal(12, "Paired"))

#wykres
ggplot(data=czas_wypozyczenia, aes(x= reorder(`miesiąc`, c(1:12)), y=`srednia długość podróży [min]`, fill = `miesiąc`)) +
  geom_bar(stat="identity")+
  scale_fill_manual(values = paleta)+
  scale_x_discrete(labels=c("STY", "LUT", "MAR", "KWI", "MAJ", "CZE", "LIP", "SIE", "WRZ", "PAZ", "LIS", "GRU"))+
  xlab("")+
  ggtitle("Średnia długość podróży w poszczególnych miesiącach")+
  theme(legend.position = "none")
```
```{r, include=TRUE}
# kod generujący wykres ruchu w ciągu roku
ruch <- lapply(months,  FUN = nrow)
ruch <- unlist(ruch)
names(ruch) = c("STY", "LUT", "MAR", "KWI", "MAJ", "CZE", "LIP", "SIE", "WRZ", "PAZ", "LIS", "GRU")
palette(brewer.pal(11, "Spectral"))
barplot(ruch, las = 1, col = c(5, 6, 7 ,5, 4, 3, 2, 1, 11, 10, 9, 8), ylim = c(0, 50000), at = NULL)
ticks<-c(0, 10000,20000,30000,40000, 50000)
axis(2,at=ticks,labels=c("0", "10.000", "20.000", "30.000", "40.000", "50.000"), las = 1)
axis(1, at = seq(0.6, 14, length.out = 12), labels = names(ruch))
title("Liczba wypożyczonych rowerów w ciągu roku")
```
```{r, include=TRUE}
ggplot(data=dane_do_wykresu, aes(x=`rok urodzenia`, y=`liczba osób`, fill = as.factor(gender))) +
  geom_bar(stat="identity")+
  geom_text(aes(y=0, label=10), vjust=1.6, 
            color="white", size=3.5)+
  scale_fill_brewer(palette = "Dark2", name = "Płeć", labels = c("Brak danych", "Mężczyzna", "Kobieta") )+
  ggtitle("Chrarakterystyka użytkowników")
```